#!/usr/bin/env ruby

require "json"
require "mote"
require "redcarpet"

class Site
  include Mote::Helpers

  def initialize(content)
    @content = content
  end

  def generate
    return mote("templates/online.mote", content: markdown, toc: toc)
  end

  def markdown
    options = { tables: true, fenced_code_blocks: true }
    renderer = Redcarpet::Render::HTML.new(with_toc_data: true)

    return Redcarpet::Markdown.new(renderer, options).render(@content)
  end

  def toc
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC)

    return renderer.render(@content)
  end
end

puts(Site.new(File.read(ARGV[0])).generate)
