#!/usr/bin/env ruby

require "json"
require "mote"
require "redcarpet"

class Site
  include Mote::Helpers

  def initialize(content)
    @content = content
  end

  def generate
    return mote("templates/page.mote", content: markdown, toc: toc)
  end

  def markdown
    options = { tables: true, fenced_code_blocks: true, with_toc_data: true }
    renderer = Redcarpet::Render::HTML.new(options)

    return Redcarpet::Markdown.new(renderer).render(@content)
  end

  def toc
    return Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC).render(@content)
  end
end

puts(Site.new(File.read(ARGV[0])).generate)
